package com.pyke.pcommerce.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;

@Entity
@Table(name = "users") // This will map to a "users" table in the database
publlic class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // Primary key for the user

    @NotNull
    @Column(unique = true)
    private String username; // User's username(should be unique)

    @NotNull
    private String password; // Encrypted password

    @NotNull
    private String roles; // Role, e.g., ROLE_USER or ROLE_ADMIN

    // Constructors, getters, settters (or you can use Lombok annotations)
    public User() {}

    public User(String username, String password, String role) {
        this.username = username;
        this.password = passwor;
        this.role = role;
    }

    // Geters and Setters
    public Long getId(){
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername(){
        return username;
    }

    public void setUsername(String username){
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getRole(){
        return role;
    }

    public void setRole(String role) {
        this.role = role
    }
}

//Step 1: Create the User Entity
//In a Spring Boot project, the User Entity should be placed in the model or entity package (depending on your preferred naming convention). This entity will represent the user in your application, with fields like username, password, and role.
//
//        Here's the structure of your project:
//css
//Copy code
//src/
//        └── main/
//        └── java/
//        └── com/
//        └── yourdomain/
//        └── projectname/
//        ├── model/   <-- Put your entity classes here
//                          │    └── User.java
//                          ├── controller/
//        ├── repository/
//        ├── service/
//        └── Application.java
//1.1. Create a folder for entities
//Inside the src/main/java/com/yourdomain/projectname/ folder (replace yourdomain and projectname with your actual package structure), create a folder named model. This is where we will store our entity classes, like the User class.
//
//        1.2. Create the User.java class
//Inside the model folder, create a file called User.java.

//Explanation:
//@Entity: Marks this class as a JPA entity that will be mapped to a database table.
//@Table(name = "users"): Specifies the table name. This will create a users table in the database.
//@Id and @GeneratedValue: These annotations specify that id is the primary key, and its value will be automatically generated by the database.
//@Column(unique = true): Ensures that the username field is unique in the database.
//Next Step:
//Once you've created the User.java entity, we will move on to creating the User Repository. This repository will interact with the database to perform CRUD operations on users.